name: Build Flet APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Setup Java (Requis pour compiler du Android)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: |
          pip install flet

      - name: Create Flutter Project & Build
        run: |
          # 1. On demande à Flet de générer le projet Flutter natif (sans lancer le build apk lourd)
          flet pack main.py --output build_flutter
          
          # 2. On entre dans le projet Flutter généré
          cd build_flutter
          
          # 3. On récupère les paquets Flutter requis
          flutter pub get
          
          # 4. C'est Flutter qui compile l'APK directement !
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build_flutter/build/app/outputs/flutter-apk/app-release.apk
